# Generated by Django 5.1.6 on 2025-02-11 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='status',
            field=models.CharField(blank=True, choices=[('ativo', 'Ativo'), ('cancelado', 'Cancelado'), ('atrasado', 'Atrasado')], max_length=10, null=True),
        ),
    ]
