# Generated by Django 5.1.6 on 2025-02-11 17:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0002_alter_client_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='status',
            field=models.CharField(blank=True, choices=[('Ativo', 'Ativo'), ('Cancelado', 'Cancelado'), ('Atrasado', 'Atrasado')], max_length=10, null=True),
        ),
    ]
