# Generated by Django 5.1.6 on 2025-02-11 19:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0003_alter_client_status'),
        ('tags', '0002_alter_tag_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='tags',
            field=models.ManyToManyField(related_name='clients', to='tags.tag'),
        ),
    ]
